### ISSUE TITLE
Name collision with commercial plug-in

### ISSUE THREAD

**Issue by CasperBraske** [luizbills/shipping-simulator-for-woocommerce#26]
A well-known commercial plugin already uses the string "wc_shipping_simulator" in several features, namely the Ajax request action. 
Can we do anything about it.

[Coloquei em inglês porque é o que eu tomo por padrão quando não tem uma recomendação no repo]

PT: Um plugin conhecido usa a string "wc_shipping_simulator" em muitas funcionalidades, como a própria requisição Ajax.
O que pode ser feito a respeito?

**Comment by luizbills** [comment]
Você está usando 2 simulador de frete?

**Comment by CasperBraske** [comment]
Eu não "uso", na verdade. Eu preciso dar suporte a calculadoras nos meus plugins.
Na verdade, pensando bem, no caso em que eu usei o nome da action, poderia ser resolvido com filtros. Logo volto com uma proposta melhor.

**Comment by luizbills** [comment]
Mas então, o que um hook tem a ver com dar suporte? Não entendi.
Para dar suporte, você precisa apenas verificar com `is_plugin_active( 'shipping-simulator-for-woocommerce/main.php' )` ou `class_exists( "Shipping_Simulator\\Core\\Main" )`.
