### ISSUE TITLE
Error in file autoload.php before install

### ISSUE THREAD

**Issue by diegonaranjo** [luizbills/shipping-simulator-for-woocommerce#44]
Hi there!
I would like to try the plugin but after installing it, I get this error that does not allow me to use it.

**Error on Shipping Simulator for WooCommerce plugin activation:
/home/digitari/public_html/wp-content/plugins/shipping-simulator-for-woocommerce-main/vendor/autoload.php does not exist**

I have Woocommerce 7.3.0. Thank you!!!

**Comment by luizbills** [comment]
Just download from https://wordpress.org/plugins/shipping-simulator-for-woocommerce/#developers or via "install plugins" on your wordpress instalation.
