### ISSUE TITLE
Plugin não fornece resultados para a pesquisa

### ISSUE THREAD

**Issue by beupjourney** [luizbills/shipping-simulator-for-woocommerce#49]
Olá, boa tarde, tudo bem? 

Por favor, estou com problemas na atualização dos dados de frete na página do produto. O plugin retorna apenas a informação abaixo, não retorna os valores. Estou com os plugins do Cláudio Sanches ativos e configurados. O cálculo de frete na página de finalização está calculando, o que demonstra também que os produtos estão com peso e dimensões cadastradas, mas na página do produto não está dando certo. Teria algum passo adicional a ser feito? Obrigada! 

Mensagem: 
Infelizmente, neste momento, este produto não pode ser entregue na região informada.
MODO DE DEPURAÇÃO ATIVADO
Tipo do produto: simple
ID do produto: #4139
Tem peso? Sim
Tem dimensões? Sim
Essa caixa não aparece para seus clientes.

**Comment by luizbills** [comment]
Desative todos os seus plugins, exceto o WooCommerce, o Simulador e o Correios. Veja se resolve. Se sim, é algum conflito. Então, depois pegue as informações de status do seu site e envie aqui. Você pode pegar essas informações na página: https://seusite.com.br/wp-admin/admin.php?page=wc-status

**Comment by beupjourney** [comment]
Era um conflito mesmo, muito obrigada. Com o plugin "Hide Shipping Method For WooCommerce"..

**Comment by luizbills** [comment]
De nada.
