### ISSUE TITLE
Problema ao exibir prazo de entrega (jadlog datadev)

### ISSUE THREAD

**Issue by fabioboni** [luizbills/shipping-simulator-for-woocommerce#75]
Opa, o plugin funciona muito bem, estou utilizando o mesmo com o plugin do correios do claudio sanches e com o datadev jadlog, porém, apesar de mostrar o método da jadlog e o custo não exibe o prazo de entrega, o prazo do correios funciona normal para todos os métodos, porém o da jadlog não, no carrinho/finalização de compra o prazo aparece, o plugin do datadev é praticamente uma cópia do dos correios, apenas adaptado para a transportadora, alguma sugestão de como posso corrigir para apresentar o prazo?

**Comment by luizbills** [comment]
Envia o link do plugin.

**Comment by fabioboni** [comment]
opa, segue o link abaixo:
https://br.wordpress.org/plugins/datadev-jadlog-for-woocommerce/

**Comment by luizbills** [comment]
Testa esse snippet:

```php
add_filter( 'wc_shipping_simulator_integration_estimating_delivery_check_rate', '__return_true', 20 );
```

**Comment by fabioboni** [comment]
funcionou!, muito obrigado

**Comment by luizbills** [comment]
Show! Será pradrão nas próximas versões então. Assim que eu puder atualizarei.
