### ISSUE TITLE
Campo "Digite seu CEP" fica preenchido com ultimo CEP consultado ao invés de ficar em branco mostrando o Placeholder

### ISSUE THREAD

**Issue by fmdonini** [luizbills/shipping-simulator-for-woocommerce#80]
Boa tarde!

Estou enfrentando um problema com o placeholder do campo "Digite o seu CEP". Ele está sempre ficando preenchido com o último CEP consultado, em vez de permanecer com o texto "Digite seu CEP". Mesmo tendo preenchido "Digite seu CEP" nas configurações do plugin.

Você saberia o que pode estar causando esse problema?

**Comment by luizbills** [comment]
Não é o campo que já está vindo preenchido?

**Comment by fmdonini** [comment]
Para mim, está aparecendo preenchido, mesmo quando não estou logado e estou acessando através do navegador no modo anônimo. Onde posso encontrar a opção "Atualizar o endereço com o CEP digitado no simulador" para verificar se desabilitando isso resolve o problema?

Seria a opção "Atualizar endereço do cliente"? No meu caso, está configurado como "Não atualizar".

**Comment by luizbills** [comment]
Tem link?

**Comment by fmdonini** [comment]
https://radiocell.com.br/bateria-ntn9858c-para-radio-motorola-xts2250-xts2500-xts1500/

**Comment by luizbills** [comment]
O mais estranho é que só aconteceu comigo nesse produto do link. Em outros produtos não acontece.

Faça uma cópia do seu site para realizar mais testes. Então lá você desativa todos os outros plugins e deixa só o WooCommerce e o simulador de frete ativados, para ver se o bug para.

Você usa algum plugin de cache ou cloudflare?

**Comment by luizbills** [comment]
Outra coisa, nas configurações do woocommerce, na aba "Geral", confere se a opção **Localização padrão do cliente** está com algum valor diferente de "Nenhuma localização por padrão".

**Comment by fmdonini** [comment]
> O mais estranho é que só aconteceu comigo nesse produto do link. Em outros produtos não acontece.
> 
> Faça uma cópia do seu site para realizar mais testes. Então lá você desativa todos os outros plugins e deixa só o WooCommerce e o simulador de frete ativados, para ver se o bug para.
> 
> Você usa algum plugin de cache ou cloudflare?

Pois é..  Antes estava acontecendo em outros produtos..  Agora todos os outros estão normais e só esse ficou "gravado" o cep rsrs

Uso plugin de cache mas já limpei todos os caches varias vezes. Uso cludflare tb.
Vou tentar realizar os testes que falou

**Comment by fmdonini** [comment]
Acho que resolveu. Veja novamente o link anterior por aí , por favor

Limpei outros caches de JS/css que eu havia esquecido de limpar

**Comment by luizbills** [comment]
> Outra coisa, nas configurações do woocommerce, na aba "Geral", confere se a opção **Localização padrão do cliente** está com algum valor diferente de "Nenhuma localização por padrão".

Chegou a mudar essa opção do woocommerce que citei?

**Comment by fmdonini** [comment]
Está como "nenhuma localização por padrão". Não mexi nisso.

**Comment by luizbills** [comment]
E de onde era aquele CEP? vc chegou a reconhecer de alguma parte da sua loja?

**Comment by fmdonini** [comment]
Foi de alguma simulação. Bom. . parece estar normal agora. Por aí também sumiu aquele CEP?

Vou marcar como resolvido e continuar monitorando, ok?
Muito obrigado pela ajuda!

**Comment by fmdonini** [comment]
Provavelmente foi o cache de JS, acredito

**Comment by luizbills** [comment]
Sumiu aqui também. Minha hipótese é que seu plugin de cache está fazendo cache mesmo de usuários logados, o que é meio arriscado e quase sempre dá problemas. Vê se tem alguma opção de não fazer cache de usuários que estão logados.

Por hora, estou fechando essa issue. Se precisar reabrimos.
