### ISSUE TITLE
Problemas para calcular o "rates" dos packages. Todos retornando vazio.

### ISSUE THREAD

**Issue by otavioserra** [luizbills/shipping-simulator-for-woocommerce#86]
Olá.

Estou tendo problemas no simulador de frete. Estou debugando seu código para ver se encontro onde pode está tendo problema. Dentro da classe Request quando há requizições ajax, dispara o método calculate_shipping. Que por sua vez instancia a classe Shipping_Package e executa o método calculate_shipping. Dentro deste método verifiquei que sempre o resultado da variável $result[0]['rates'] é vazio. Já tentei excluir sessões do woocoomerce e etc. Mas sempre este valor tem sido vazio.

Você poderia me ajudar em onde posso olhar para poder encontrar o que pode estar errado?

Obrigado

**Comment by luizbills** [comment]
Mas o que exatamente você está testando? Funciona no carrinho?

**Comment by otavioserra** [comment]
> Mas o que exatamente você está testando? Funciona no carrinho?

Não está funcionando em nenhum dos dois. E antes estava, não foi feito nenhuma alteração. Estou usando as últimas versões de todos os plugins Woocommerce vinculados ao frete.

PHP v8.1
WooCommerce - v8.1.1
Claudio Sanches - Correios para WooCommerce v4.1.8
Frenet Shipping Gateway for WooCommerce - v2.1.13
Simulador de Frete para WooCommerce - v2.3.2

Como te disse, o problema está na variável 'rates' que por algum motivo está vazia, não importa o que faça. Não sei se isso é o problema, mas pelo seu código só retorna valor correto caso essa variável tenha algum valor dentro do array. 

Sempre o retorno do seu plugin é: "Infelizmente, neste momento, este produto não pode ser entregue na região informada."

**Comment by luizbills** [comment]
Como você disse, nem no carrinho está funcionando. Então provavelmente é esse plugin da frenet. Entre em contato com o desenvoldedor daquele plugin.

Caso você consiga fazer funcionar no carrinho, provavelmente voltará a funcionar no simulador.
